"""Constants and the mjlab EntityCfg for the jumper hexapod.

A 22-DoF heterogeneous hexapod: two 5-DoF front arms (in FOOT mode the grippers
are locked and it walks on the rear jaw pads, `*F_palm_pad_b_link`) plus four 3-DoF
middle and rear legs.

The model is **Liuzu V1.6**, generated by `assets/jumper/tools/build_jumper.py` from
the CAD team's URDF export. Two geom sets coexist in one XML:

| Name | Contents |
|---|---|
| `<body>_visual`  | the link's mesh, display only |
| `<body>_meshcol` | the link's mesh, the collision geometry |

**There is one collision scheme: hybrid** -- foot meshes at source resolution plus
reduced geometry for every other link. It is what makes contact fidelity affordable
at scale: on the previous model, measured over 4096 environments, full meshes
everywhere cost 0.64 s per iteration and 61 GiB of `MjModel` copies, against 0.39 s
for the hybrid.

On V1.6 the reduced half is each link's convex hull, decimated to 64 sampled
directions -- the same density V1.5's source-provided collision meshes used.
See `_LINK_MESH`, which records why the exact hull was tried first and what it
cost.

The earlier all-`mesh` and all-`primitive` schemes have been deleted: the choice is
settled, and keeping them would give every config function a parameter that always
takes its default while tempting new experiments to rediscover a known trap.

Both geom sets stay in the XML. `CollisionCfg` with `disable_other_geoms=True`
zeroes contype/conaffinity on whatever is not selected, so nothing unselected takes
part in simulation -- and keeping dead geometry out of the file matters beyond
tidiness: at large environment counts the native backend strips visual meshes and
the live viewer then draws collision geometry, so anything left lying around
**makes the picture lie** about what is being simulated.

## What belongs in this file

**Facts about the hardware.** There is one chassis, one IMU, one set of current
sensors and one servo curve, so there is one value and four tasks read it:
`EFFORT_LIMIT` is the measured torque plateau, `STAND_Z` is how tall the robot
stands, `IMU_ANG_VEL_NOISE` is what a gyro bolted to a walking hexapod reads.

**Not tuning.** A weight, a reward target or a curriculum rung is a choice a gait
makes, and it belongs in that task's `env_cfg.py` even when all four agree --
`velocity_env_cfg` raises rather than defaulting for those. The test of which pile
a number belongs in is whether two gaits on this robot could reasonably want
different values: if yes it is the task's, if no it is here.

`docs/DESIGN.md` section 14 has the reasoning, and `tests/test_task_parity.py`
enforces the half of it that can be enforced.
"""

from __future__ import annotations

from functools import partial
from pathlib import Path

import mujoco
from mjlab.entity import EntityArticulationInfoCfg, EntityCfg
from mjlab.utils.spec_config import CollisionCfg

from .actuator import PLATEAU_TORQUE, ServoCurveActuatorCfg
from .assets import JUMPER_XML

##
# Assets
##


def get_spec(asset: Path | None = None) -> mujoco.MjSpec:
    """Compile the model. ``asset`` of None uses the default jumper.xml.

    Changing the model changes only the XML: the joint names, HOME pose and foot
    geom names below are still written against the default asset, so a
    structurally different model fails while the environment is being built rather
    than quietly producing wrong results.
    """
    path = Path(asset) if asset is not None else JUMPER_XML
    if not path.exists():
        hint = (
            "First run:\n"
            "  python assets/jumper/tools/build_jumper.py --src <source repository> "
            "--out assets/jumper/jumper.xml"
            if path == JUMPER_XML
            else "Check the path given to --model."
        )
        raise FileNotFoundError(f"{path} not found. {hint}")
    return mujoco.MjSpec.from_file(str(path))


##
# Standing pose
##

# Re-solved for the V1.6 model by `assets/jumper/tools/calibrate_home.py`, which
# takes the previous revision's pose as its seed and levels the six feet again.
# It barely had to: the new CAD moved the joint anchors 2-9 mm, which left the
# feet spanning **0.683 mm** in height, and restoring coplanarity cost 29 mrad at
# each front wrist and 6 mrad at each ankle. Everything else is the pose that was
# solved for the extended stance upstream, unchanged.
#
# The properties that pose was chosen for all survive the move, measured on this
# model rather than assumed:
#
# - at least 12% of the limit range as margin on every gait joint (worst 12.5%,
#   RR_ankle)
# - holdable by kp=10 / kd=0.5, needing 0.2296 N*m at the worst joint (LM_knee),
#   13.1% of the servo's 1.7464 N*m plateau, with **no** actuator saturated
# - no self-contact at rest
#
# The pose is **calibrated against mesh collision**: the six contact points are
# the `*_meshcol` geoms of the bodies in `FEET`, coplanar to 0.001 mm at these
# rounded values, with the lowest sitting 3.4 um above the ground at STAND_Z.
#
# **Both gripper joints home at 0.0**; they were -1.0 each. The two are mirrored
# -- the left gripper's range is [-1.6, 0.1] and the right one's is [-0.1, 1.6]
# (V1.6 widened both ends by 0.1 rad; they used to stop exactly at 0) -- so the
# shared -1.0 sat inside the left range but **outside the right one by a full
# radian**. MuJoCo pinned RF_J4_joint at its limit and the PD pushed
# kp * 1.0 = 10 N*m into the constraint forever: measured saturated on 99.9% of
# steps, in every run this repository has ever done, while the robot stood and
# trained normally throughout. Standing at the corrected pose saturates **no**
# actuator and its worst joint asks 0.2296 N*m of the 1.7464 available, so the
# whole of that saturation was one joint fighting a limit it could not reach.
# Nothing reported it because the grippers
# are not in `GAIT_JOINTS`, so no reward, termination or observation looked at
# them, and `actuator_force` deliberately drops their two columns.
#
# The lesson is cheap to act on: a home pose is the one configuration every run
# starts from, and nothing in the pipeline checks it against the joint limits.
# `tests/test_servo_curve.py::test_home_pose_is_inside_the_joint_limits` does.
HOME: dict[str, float] = {
    "LF_J0_joint": -0.5507, "LF_J1_joint": -1.0658,
    "LF_J2_joint": -0.4408, "LF_J3_joint": -1.374, "LF_J4_joint": 0.0,
    "RF_J0_joint": 0.5524, "RF_J1_joint": -1.066,
    "RF_J2_joint": 0.4414, "RF_J3_joint": 1.4173, "RF_J4_joint": 0.0,
    "LM_J0_joint": 0.0012, "LM_J1_joint": 0.5356, "LM_J2_joint": -1.8271,
    "RM_J0_joint": -0.0012, "RM_J1_joint": -0.5376, "RM_J2_joint": 1.8313,
    "LR_J0_joint": 0.6313, "LR_J1_joint": 0.5534, "LR_J2_joint": -1.8648,
    "RR_J0_joint": -0.6326, "RR_J1_joint": -0.5548, "RR_J2_joint": 1.8678,
}

STAND_Z = 0.10647

# The canonical leg order (the tripod gait's two groups: LF/RM/LR and RF/LM/RR)
LEGS: tuple[str, ...] = ("LF", "RF", "LM", "RM", "LR", "RR")

# Where the six foot sites sit in the body frame at HOME, in metres, in `LEGS`
# order. x forward, y left; the z column is dropped because every foot is within
# 0.2 mm of the same height and nothing reads it.
#
# **A fact about the robot standing at HOME, so it belongs here** rather than in a
# task: it follows from the URDF and `HOME` above and from nothing a gait chooses.
# What reads it is `tasks/hexa/posture/`, which measures the body's yaw *relative
# to where its feet are* by least-squares aligning the current footprint onto this
# one -- so this is the footprint that means "not twisted".
#
# Measured, not copied from CAD: load `assets/hexa/hexa.xml`, write `HOME` into
# `qpos`, `mj_forward`, and express each foot site in the base link's frame --
#
#     p_body = R_base^T (site_xpos - base_xpos)
#
# `tests/test_posture_stance.py` re-derives it exactly that way and fails on a
# disagreement past 1 mm. That test is the point of writing the numbers down: a
# new robot revision replaces `hexa.xml` in place, and a stale footprint here
# would not raise -- it would quietly redefine zero twist as a few degrees of
# twist, which is a bias the policy would then be trained to hold.
# How far the foot site sits above the ground when the pad it belongs to is
# resting on it, in metres.
#
# The site is at the centre of the silicone pad, not at its contact point, so a
# body height measured as "base minus feet" reads 8.9 mm short of the height the
# robot is actually standing at. Adding this back makes it read `STAND_Z` at HOME,
# which is what lets `tasks/hexa/posture/` quote its height command in the same
# units as every other height in this repository.
#
# Derived, not assumed: `STAND_Z` (0.10647, the height at which the lowest
# collision geom is a few um off the ground) minus the mean foot-site depth in
# `NOMINAL_FOOT_XY`'s measurement, 0.097641.
FOOT_SITE_Z = 0.008829

NOMINAL_FOOT_XY: tuple[tuple[float, float], ...] = (
    (0.187123, 0.072818),    # LF
    (0.183590, -0.068983),   # RF
    (-0.006794, 0.197435),   # LM
    (-0.008167, -0.197148),  # RM
    (-0.140528, 0.159528),   # LR
    (-0.141648, -0.158449),  # RR
)

# The six leaf bodies that actually carry contact -- contact force queries must
# use these names, because the parent links carry none of it.
#
# **The front pair changed with the V1.6 model.** The single fixed jaw the arm
# used to walk on (`*F_palm_pad_b_link`) is now two silicone pads on the same link,
# `*F_palm_pad_f_link` 15.8 mm in front of `*F_palm_pad_b_link`. Only the rear pad
# is a foot here; that is a decision, not a reading of the CAD, and the front pad
# sits in `TIP_LINKS` instead.
FEET: tuple[str, ...] = (
    "LF_palm_pad_b_link", "RF_palm_pad_b_link",
    "LM_foot_tip_link", "RM_foot_tip_link",
    "LR_foot_tip_link", "RR_foot_tip_link",
)

# The upper leg segments: the two shoulder links and the forearm on the 5-DoF
# arms, the two upper links on each 3-DoF leg. The V1.6 export names every moving
# link `<leg>_J<n>_link`, so what used to be `shoulder_yaw / shoulder_pitch /
# forearm` is now `J0 / J1 / J2`, and `thigh / calf` is `J0 / J1`.
LIMB_LINKS: tuple[str, ...] = (
    "LF_shoulder_link", "LF_upper_arm_link", "LF_forearm_link",
    "RF_shoulder_link", "RF_upper_arm_link", "RF_forearm_link",
    "LM_hip_link", "LM_thigh_link", "RM_hip_link", "RM_thigh_link",
    "LR_hip_link", "LR_thigh_link", "RR_hip_link", "RR_thigh_link",
)

# The 20 joints the policy controls: everything but the two grippers, which in
# FOOT mode are held at home by PD
#: The two gripper joints, named so the filter below cannot go stale silently.
#: They used to be `*_finger_joint` and a suffix test found them; the v1.6.1
#: export renames every joint to `<leg>_J<n>_joint`, under which `_J4_joint` is
#: a gripper on the front pair and does not exist anywhere else -- but a suffix
#: test on `_J4_joint` would be a rule about numbering rather than about what
#: the joint is. Naming them is one line and cannot drift.
GRIPPER_JOINTS: tuple[str, ...] = ("LF_J4_joint", "RF_J4_joint")

GAIT_JOINTS: tuple[str, ...] = tuple(
    j for j in HOME if j not in GRIPPER_JOINTS
)

##
# Actuators: MIT-mode joints
##

# kp=10 / kd=0.5, and the torque bounded by the servo's measured torque-speed
# curve rather than by a constant. armature and frictionloss come from the MJCF.
#
# **EFFORT_LIMIT was 2.0 and is now the measured plateau, 1.7464 N*m.** The old
# value had no recorded provenance -- it appeared here, in the MJCF's
# actuatorfrcrange and in the exported contract, and no file said whether it was
# a continuous rating, a peak, or a number inherited from the Isaac config. The
# hardware's plateau is 12.7% lower, so every previous run had a slightly
# stronger robot than exists. Standing does not notice: the six legs need at most
# 0.2296 N*m at HOME, 13.1% of the plateau (measured on the V1.6 model, see
# assets/jumper/motor/README.md).
#
# The name stays `EFFORT_LIMIT` because velocity_env.py and scripts/export.py
# both read it; what changed is that it is now a cap **on top of** the curve
# rather than the only bound.
#
# **It is a peak rating, holdable for 300 ms.** After that the actuator's
# thermal state derates the ceiling to `min(1.2 N*m, curve(speed))`; the two
# constraints cross at 40.19 rad/s, above which the curve was already the
# tighter of the two. So `EFFORT_LIMIT` is the *most* this robot can ever
# produce, not what it can produce for as long as it likes.
EFFORT_LIMIT = PLATEAU_TORQUE
STIFFNESS = 10.0
DAMPING = 0.5
ARMATURE = 0.0015

def make_actuator_cfg(effort_limit: float = EFFORT_LIMIT) -> ServoCurveActuatorCfg:
    return ServoCurveActuatorCfg(
        target_names_expr=(".*_joint",),
        stiffness=STIFFNESS,
        damping=DAMPING,
        effort_limit=effort_limit,
        armature=ARMATURE,
    )


JUMPER_ACTUATOR_CFG = make_actuator_cfg()

JUMPER_ARTICULATION = EntityArticulationInfoCfg(
    actuators=(JUMPER_ACTUATOR_CFG,),
    soft_joint_pos_limit_factor=0.9,
)

# Action scale: the policy output is multiplied by it and added to the home pose
# to form the position target.
#
# **Do not use the formula mjlab applies to Go1**, `0.25 * effort / stiffness`.
# It holds for Go1's actuators (hip 0.373, knee 0.249 rad) but gives 0.044 rad
# here: this robot pairs kp=10 with a 1.7464 N*m plateau, so a position error of
# only 0.175 rad saturates the torque, and taking a quarter of that leaves 0.044.
# (The argument was first written against the old 2.0 N*m figure, where the
# numbers were 0.2 and 0.05; the real plateau makes the trap slightly worse.)
#
# Measured consequence: at 0.05 rad the policy **cannot lift a foot at all**. With
# a 0.16 m leg segment, raising the foot 0.03 m needs about 0.19 rad of joint
# rotation, which at scale=0.05 demands a 3.8-sigma action that a Gaussian policy
# essentially never samples. Trained for a full 3000 iterations with that value,
# vx/vy/wz tracking were all 0% and mean torque reached 2% of the limit -- the
# robot was not unwilling to walk, it had no usable action range.
#
# 0.25 is the value tuned on Isaac for **the same robot with the same PD gains**.
# It deliberately allows the policy to command position targets that saturate
# torque -- a position target is a setpoint, saturation during transients is
# expected, and that is normal in legged RL.
ACTION_SCALE = 0.25

JUMPER_ACTION_SCALE: dict[str, float] = {j: ACTION_SCALE for j in GAIT_JOINTS}

##
# The collision scheme
##

#: The segments between the last upper-leg link and the toe or jaw tip.
#:
#: They **took no part in collision at all** originally: `LIMB_LINKS` stopped at
#: the forearm and the calf, these segments were left out, and
#: `disable_other_geoms=True` zeroed their `*_meshcol` contype. The consequence was
#: that they **passed straight through the ground**: in one snapshot of 64
#: environments, including them in collision produced 46 ground contacts, meaning
#: those contacts previously had neither a physical response nor any cost.
#:
#: Such contact should not happen -- the toe and claw tips are what should touch
#: down. **But this only brings them into collision; it adds no penalty.**
#: Collision is physical correctness (not colliding means passing through), while a
#: penalty changes the learning problem and whether and how heavily to add one
#: should be decided by training results. `TIP_GEOMS` is exported ready for that:
#: configure a `ContactSensorCfg(primary=TIP_GEOMS, secondary="terrain")` and wire
#: it to `mdp.self_collision_cost` (which is what mjlab does for G1 self-collision;
#: see `rl/mjlab/tasks/velocity/config/g1/env_cfgs.py`).
#:
#: **`*F_palm_pad_f_link` belongs in this set, and it is worth saying why it is
#: not a foot.** It is the front pad of the front jaw, mounted on the same link as
#: the rear pad and at the same height in the CAD to within 2 um -- from the
#: numbers alone the two look interchangeable. In the standing pose they are not:
#: the wrist turns the jaw nearly upright, so the front pad sits **16.55 mm above**
#: the rear one (measured, this model, at HOME) and never reaches the ground. The
#: rear pad is the foot; the front pad is a segment that should not touch, which is
#: exactly what this set is for.
TIP_LINKS: tuple[str, ...] = (
    # The front legs are 5-DoF arms; in FOOT mode they walk on the rear palm pad
    # (`*F_palm_pad_b_link`), with the palm carrying it, the finger and the
    # finger tip beyond it, the front pad, and the two grip inserts the v1.6.1
    # export added inside the jaw
    "LF_palm_link", "LF_finger_link", "LF_finger_tip_link", "LF_palm_pad_f_link",
    "LF_finger_grip_insert_link", "LF_palm_grip_insert_link",
    "RF_palm_link", "RF_finger_link", "RF_finger_tip_link", "RF_palm_pad_f_link",
    "RF_finger_grip_insert_link", "RF_palm_grip_insert_link",
    # Middle and rear legs: the segment between the thigh and the foot tip
    "LM_calf_link", "RM_calf_link", "LR_calf_link", "RR_calf_link",
)

#: The foot contact meshes -- **original meshes, not hulled**. They are what
#: actually touches the ground, and they are excluded from
#: `tools/hull_collision.py` for that reason: a hull's flat facets would change
#: when the foot lands. 9815 of the stripped model's 38477 vertices are these six.
_FOOT_MESH = tuple(f"{f}_meshcol" for f in FEET)

#: Collision geometry for every other link: a **64-direction decimated convex
#: hull**, written by `tools/hull_collision.py -k 64` and named `*_col`.
#:
#: **k=64 is not a tuning choice, it is the value the previous model shipped.**
#: V1.5's source provided its own `*_col` meshes and they are 56-64 vertex
#: hulls -- the Euler relation F = 2V - 4 holds on every one of them, 64 -> 124
#: faces, 59 -> 114 -- so the collision geometry this robot has always trained
#: against was a 64-direction hull decimation.
#:
#: That was learned the expensive way. The exact hull (`-k 0`) was shipped
#: first, on the argument that MuJoCo collides a mesh by its hull anyway so the
#: swap costs nothing -- true, and measured at 0.008 um of support-function
#: error. But the comparison was against V1.6's *full meshes*, which nothing had
#: ever run, rather than against V1.5, which is what the 12-14 GB of VRAM at
#: 4096 environments came from. Against the real baseline the exact hull is a
#: **6.3x regression** in collision faces and it filled a 24 GB card.
#:
#: Collision faces, which is the quantity that scales:
#:
#:     V1.5             9296 foot +  2954 other = 12250   (plus 15 primitives)
#:     V1.6 exact hull 19606 foot + 57204 other = 76810
#:     V1.6 k=64       19606 foot +  3538 other = 23144
#:
#: k=64 puts the non-foot half back where V1.5 had it. What remains above V1.5
#: is entirely the feet, which are excluded from hulling on purpose and whose
#: V1.6 CAD is denser: the front pad is 5940 faces against V1.5's 1704.
#:
#: `check_model_slim.py`, for the native backend which copies one `MjModel` per
#: environment:
#:
#:     full meshes    106.75 MB  ->  106.73 MB stripped  ->  54.65 GB at N=512
#:     exact hull     117.05 MB  ->   18.72 MB stripped  ->   9.59 GB at N=512
#:     k=64 hull      105.78 MB  ->    5.03 MB stripped  ->   2.58 GB at N=512
#:
#: The price is real and is in the safe direction: decimation moves a hull only
#: **inward** (the sampled support points lie on the true hull), by at most
#: 7.81 mm here, on `upper_shell_link`. Contact triggers slightly later, never
#: earlier, and never on a foot -- `_FOOT_MESH` is excluded.
#:
#: The stripped size used to save **0.0%**, and hulling is what unblocked it:
#: `strip_visual_meshes` drops mesh assets no colliding geom refers to, and
#: before this `<body>_visual` and `<body>_meshcol` named the *same* asset, so
#: there was nothing to drop.
#:
#: Hulls rather than capsules, for the reasons the previous model established:
#:
#: - **A closer fit.** A capsule approximates a link as a cylinder; a hull follows
#:   the real shape.
#: - **Never fatter than the mesh.** A hull contains every extreme point of the
#:   original, so its lowest point is identical, whereas a fitted capsule bulges
#:   outward -- measured in the old standing pose, the capsules around the gripper
#:   segments sat 1.6-9.8 mm below the foot meshes, and the robot would stand on
#:   its palms rather than its jaws.
#:
#: What a hull does cost is concavity: it bridges every hollow, so the upper
#: shell collides as a solid block and a gripper collides across its own open
#: jaws. That was equally true before this change -- MuJoCo was always colliding
#: the hull -- but it is invisible, so `check_hulls.py` draws it.
#: The chassis: the base and the four parts bolted to it. V1.6 added the upper
#: shell and two sensor housings; the bottom-shell revision added `display_module_link`,
#: the display. **Every one of them has to be here**, for a physical reason and a
#: rendering one.
#:
#: Physically, `upper_shell_link` is a 110 g shell covering the top of the base and
#: the sensors and display sit proud of the front face. Leaving them out of the
#: collision set means they pass through the ground -- so a robot that rolls onto
#: its back rests on nothing, exactly the failure `TIP_LINKS` was created to fix.
#:
#: For rendering, omitting even one has an effect out of all proportion.
#: `CollisionCfg(disable_other_geoms=True)` zeroes the contype of every `*_meshcol`
#: geom it was not given, leaving a non-colliding geom sitting in the collision
#: group. The live viewer hides the collision meshes by switching off whole geom
#: groups, and it will only switch a group off when **every** geom in it collides
#: (`viewer/live.py::_collision_only_groups`). One leftover disqualifies group 1
#: entirely, so all 36 collision meshes get drawn on top of the appearance meshes
#: they are coincident with. Measured with the three omitted, while the collision
#: meshes were still MuJoCo's default grey: not one pixel of the robot was red any
#: more, and the lit surfaces rendered #FCAFBE, a pale pink.
#:
#: That second failure now has a defence of its own -- `build_jumper.py` gives the
#: collision geoms the same URDF material colour as the appearance ones, so the
#: robot renders identically whichever set is drawn (measured: #F42A46 either
#: way). Keep both. The colour makes the picture survive a mistake; the list here
#: is what stops the mistake, and only the list fixes the physics.
CHASSIS_LINKS: tuple[str, ...] = (
    "base_link", "upper_shell_link", "camera_link", "tof_sensor_link",
    "display_module_link",
)

_LINK_MESH = tuple(
    f"{link}_meshcol" for link in CHASSIS_LINKS + LIMB_LINKS + TIP_LINKS
)


# Feet against the ground: condim 3 with real friction. Every other geom is close
# to frictionless (condim 1) and only provides support when the robot tips over or
# self-collides; it takes no part in the gait.
#
# **The whole tip is Shore A 60 silicone** -- the geoms kept as full meshes
# (`*F_palm_pad_b_link_meshcol`, `*_foot_tip_link_meshcol`) are the moulded part, not
# a hard shell with a pad on it. Silicone rubber is grippier than the generic
# rubber this used to assume: dry on a hard floor it runs 0.8-1.5, and it is
# contamination that costs it, dust or water pulling it down to 0.4-0.6. 1.2 is
# the clean dry figure. **This is a materials-handbook estimate, not a bench
# measurement** -- a pull test on the real foot against the real floor should
# replace it, and `JUMPER_FOOT_FRICTION_RANGE` with it.
#
# Only the first component is live: `condim=3` means the torsional and rolling
# coefficients are never evaluated. They are kept at 0.01 so that raising a foot
# to condim 4 stays a one-word change, but a silicone tip this soft does resist
# spin in reality, and at condim 3 the policy is free to pivot on a foot for
# nothing.
_FOOT_FRICTION = (1.2, 0.01, 0.01)

#: Sliding friction the feet are randomised over at startup.
#:
#: mjlab's default is (0.3, 1.2) with `operation="abs"`, which **overwrites**
#: `_FOOT_FRICTION` -- so the nominal above is what `play` sees and what training
#: never sees. The default is a generic rubber range, and against silicone it is
#: displaced low: the whole band sits at or below the clean dry figure, so nearly
#: every training environment is more slippery than any surface the robot will
#: actually walk on. That is difficulty for its own sake, on top of the contact
#: chatter fixed alongside this.
#:
#: This band is the real operating envelope instead: 0.5 is silicone with dust or
#: water on it, 1.5 is clean and dry on a hard floor.
JUMPER_FOOT_FRICTION_RANGE = (0.5, 1.5)

#: Observation noise, as the uniform half-width each sensor's reading is corrupted
#: by during training. Here rather than in `velocity_env.py` because these describe
#: **the hardware, not the gait** -- one IMU, one set of current sensors, and four
#: tasks that deploy onto them. A task with a reason to differ can still pass its
#: own; what it cannot do is differ by accident.
#:
#: **None of the three is measured on this robot**, which is the weakest provenance
#: of any constant in this file. Each is twice the middle of what general practice
#: reports, which is the usual domain-randomisation margin.
#:
#: `IMU_ANG_VEL_NOISE`. MEMS datasheet noise is 0.003-0.015 deg/s/sqrt(Hz), about
#: 0.002-0.004 rad/s in a 100-500 Hz band, and irrelevant: on a legged robot the
#: gyro reads structural vibration from the servos and the part's g-sensitivity,
#: reported at 0.05-0.2 rad/s RMS in band. Taking 0.10 and doubling gives sigma
#: 0.20, so a half-width of sqrt(3) * 0.20 = 0.35.
#:
#: `IMU_GRAVITY_NOISE`. A unit vector, so the noise reads directly as a tilt angle,
#: and the error is the attitude estimate's rather than the accelerometer's -- body
#: acceleration corrupts the gravity reference while walking, and a complementary
#: or Mahony filter on MEMS gives 1-3 deg RMS. Taking 2 deg and doubling gives
#: sigma 0.070, half-width 0.12, which reads back as 4.0 deg.
#:
#: `ACTUATOR_FORCE_NOISE` is the one with an experiment behind it. A policy trained
#: at +/-0.05 was replayed with Gaussian noise at sigma 0.0833 on this term, 512
#: envs x 500 steps, against itself on a clean observation: linear tracking error
#: +14.3%, angular +19.4%, no falls. +/-0.15 is sigma 0.0866, within 4% of the
#: variance that was measured, so it spends headroom that was demonstrated rather
#: than assumed.
#:
#: To replace the IMU pair with measurements: log `imu/output` off the robot (the
#: DDS topic is already published, see `deploy/dds/`) for a minute standing and a
#: minute stepping in place. The standing trace gives the white-noise floor and the
#: bias; **the stepping trace is the one these should match**, since that is the
#: regime the policy runs in. Then `half_width = sqrt(3) * sigma`.
#: How hard `push_robot` shoves the base, as +/- m/s on each axis. A robot fact
#: rather than a gait one: mjlab's +/-0.5 is sized for a 12 kg Go1 and this robot
#: is about 2 kg, so the same impulse is six times the disturbance and amounts to
#: flipping it over. The angular components keep mjlab's and have not been
#: calibrated.
PUSH_VELOCITY_RANGE = {"x": (-0.2, 0.2), "y": (-0.2, 0.2), "z": (-0.1, 0.1)}

IMU_ANG_VEL_NOISE = 0.35
IMU_GRAVITY_NOISE = 0.12
ACTUATOR_FORCE_NOISE = 0.15

#: Contact solver reference: time constant, damping ratio.
#:
#: This was 0.008, chosen because 0.005 hit contact resonance and the robot
#: juddered while standing. Both of those were measured **on the flat scene**, and
#: a plane is the one ground that hides the problem: MuJoCo collides a mesh against
#: a plane with a dedicated routine, while a mesh against a *box* goes through CCD
#: and yields a single contact point that flickers in and out at zero penetration.
#: 0.008 s is only 1.6x the 0.005 s timestep, below the >=2x the integrator needs,
#: so the contact was stiffer than the solver could hold and the box terrains
#: chattered.
#:
#: Measured on the rough scene, 512 envs, a policy walking a 2.5 Hz tripod, as
#: contact-state flips per foot per second -- the gait itself demands exactly 5.0,
#: so everything above that is the contact signal lying to `tripod_gait`,
#: `stance_load` and `air_time` (RTX 5090):
#:
#: | terrain                | 0.008 | 0.015 | 0.02 |
#: |------------------------|-------|-------|------|
#: | box stairs             |  6.7  |  5.7  | 5.2  |
#: | box flat (12 m tile)   | 10.3  |  8.4  | 7.3  |
#: | heightfield slope/wave |  5.4  |  5.2  | 5.2  |
#:
#: 0.02 costs nothing: standing height came out the same at every value tested,
#: height jitter goes 0.113 -> 0.128 mm, and total contact force drops from 37.9 N
#: to 33.3 N -- closer to the 29.5 N the robot actually weighs, which is bounce
#: leaving rather than support. Not softer than this: 0.03 raises jitter to
#: 0.171 mm and starts costing the heightfield columns their near-perfect signal.
#: (Those absolute figures are from a 128-env run; see `_CONTACT_SOLIMP` for why
#: only the differences within one run are worth reading.)
#:
#: Box terrain still reads worse than a plane or a heightfield (7.3 against ~5.2).
#: That residue is the CCD collider, not the solver, and no sim option reaches it:
#: `nconmax` 128 -> 1024, `ccd_iterations` 50 -> 200 and disabling MULTICCD each
#: changed nothing, and a foot `margin` made it far worse (heightfield contact
#: 0.99 -> 0.37, the robot hovering 4.6 mm high).
_CONTACT_SOLREF = (0.02, 1.0)

#: Contact impedance: d0, dwidth, width, midpoint, power.
#:
#: MuJoCo's default (0.9, 0.95, 0.001, ...) is a rigid contact -- the foot rests on
#: the surface with no measurable penetration. That is the wrong model for this
#: robot, whose tips are solid Shore A 60 silicone several millimetres thick, and
#: it is wrong in the direction that hurts: **the contact flicker is a
#: zero-penetration artefact.** A foot resting exactly on a box face gives CCD a
#: degenerate overlap it loses and regains frame to frame, and a tip that
#: compresses under load sits *inside* the surface instead.
#:
#: **It does not go as far as that argument suggests.** Measured against the
#: paving in `scenes/rough.py`, as contact blips per foot per second on the flat
#: column, the two are not alternatives and compliance is the smaller of them:
#:
#: |              | rigid | silicone |
#: |--------------|-------|----------|
#: | one 12 m box | 0.75  | 0.51     |
#: | 1.0 m paving | 0.04  | 0.01     |
#:
#: Compliance alone takes a third off and leaves the flat column an order of
#: magnitude worse than every other one; the geometry is what fixes that. What
#: compliance does earn is uniform: it roughly halves the blips on every column at
#: once -- stairs 0.04 -> 0.02, heightfield slope 0.07 -> 0.03, random_rough
#: 0.25 -> 0.13 -- which is the part no terrain change reaches.
#:
#: How much it should compress, from the material: Shore A 60 gives E ~ 3.6 MPa
#: (Gent), the tip is 8-10 mm of it over a contact patch of 20-50 mm2, and
#: standing shares 29.5 N over six feet, so F*t/(A*E) lands at 0.1-0.7 mm.
#:
#: Measured standing compression against d0 (256 envs, seeds 0 and 1 agreeing to
#: four decimals, zero actions, RTX 5090): 0.9 -> 0.00 mm, 0.8 -> 0.57 mm,
#: 0.7 -> 0.96 mm, 0.6 -> 1.57 mm. 0.8 is the last one inside the physical band;
#: 0.7 would need 15 mm of silicone under the foot.
#:
#: **Measure this with a fixed seed and a few hundred environments.** The first
#: attempt used 128 with `seed=None` and put the compression 20% low, because
#: `reset_robot_joints` randomises the pose the robot settles from and the mean
#: standing height is still moving at that sample size -- the same nominally
#: identical configuration read 0.1005 m, 0.1008 m and 0.1032 m on three runs.
#:
#: It also settles the robot down rather than stirring it up -- body height jitter
#: while standing goes 0.101 mm rigid -> 0.082 mm here -- and takes another slice
#: off the contact blips on every terrain column at once.
_CONTACT_SOLIMP = (0.8, 0.90, 0.002, 0.5, 2.0)


# ── Collision masks: ground for everyone, leg-vs-leg but never leg-vs-itself ──
#
# MuJoCo's pair test is `(contype1 & conaffinity2) || (contype2 & conaffinity1)`.
# One bit is reserved for the ground channel and one bit is given to each of the
# six legs, which lets a plain bitmask express "different legs collide, the same
# leg never does" without a single `<exclude>` pair:
#
#     leg i   contype = GROUND | bit(i)      conaffinity = ALL_LEGS & ~bit(i)
#     base    contype = GROUND               conaffinity = 0
#
#   * leg vs terrain  -> `contype_leg & 1 = GROUND` -> collides, as before.
#   * leg i vs leg j  -> `bit(i) & (ALL_LEGS & ~bit(j)) = bit(i)` for i != j
#                        -> collides, and the self-collision sensor sees it.
#   * leg i vs itself -> `bit(i) & ~bit(i) = 0` in both directions -> no contact.
#   * base vs leg     -> 0 both ways (GROUND is not in ALL_LEGS) -> no contact.
#
# Excluding same-leg pairs is what makes this safe to switch on at all, and it
# is also the physically right answer: links on one leg are adjacent by
# construction, so a gripper folded against its own wrist link is the mechanism
# doing what it was built to do, not a fault to be penalised.
#
# The mechanical reason is the collision geometry. It is a convex hull, and
# **a hull fills in concavities**, so hulls on the same leg start intersecting
# well before the real parts would touch. MuJoCo only auto-excludes parent/child
# pairs, and the offenders here are a generation or more apart. Turning
# conaffinity on wholesale (the obvious way to enable self-collision) measured
# 66 mask-allowed same-leg pairs, firing in 692 of 2000 random joint
# configurations -- 1832 contacts, led by the finger and wrist links against
# their own shoulder yaw link (`J4 x J0`, `J3 x J0` on the *same* arm), i.e. an
# arm curled onto its own shoulder. Every one of those would have been scored as a
# collision. The
# per-leg bit removes all 66 while keeping the 369 cross-leg pairs the penalty
# is actually for. That wholesale-blocking problem is the reason self-collision
# used to be switched off entirely (`conaffinity=0`).
#
# Note this is about poses reachable in motion, not the rest pose: at HOME the
# model has no self-contact under either mask. Verified in
# `tests/test_jumper_self_collision.py`.
#
# base_link stays out of the self-collision set on purpose. The ask is leg-vs-leg,
# and the base hull is the fattest one in the model; folding it in would mostly
# re-introduce hull-fill contacts against the shoulders and thighs it sits on.

#: Bit reserved for the terrain channel (terrain is contype=1/conaffinity=1).
_GROUND_BIT = 1

#: One bit per leg, starting just above the ground bit.
_LEG_BIT: dict[str, int] = {leg: 1 << (i + 1) for i, leg in enumerate(LEGS)}

#: All six leg bits OR'd together.
_ALL_LEG_BITS = sum(_LEG_BIT.values())

#: Every collision geom of a leg is named `<LEG>_<link>_meshcol`, so the leg
#: prefix alone selects them. `resolve_expr` matches in insertion order and
#: takes the first hit, so these must precede the `".*"` catch-all that base_link
#: falls through to.
_LEG_GEOM_RE: dict[str, str] = {leg: f"^{leg}_" for leg in LEGS}


def _collision_cfg(foot_names: tuple[str, ...], other_names: tuple[str, ...]) -> CollisionCfg:
    foot_re = "|".join(f"^{n}$" for n in foot_names)
    contype = {_LEG_GEOM_RE[leg]: _GROUND_BIT | bit for leg, bit in _LEG_BIT.items()}
    conaffinity = {_LEG_GEOM_RE[leg]: _ALL_LEG_BITS & ~bit for leg, bit in _LEG_BIT.items()}
    return CollisionCfg(
        geom_names_expr=foot_names + other_names,
        contype=contype | {".*": _GROUND_BIT},
        conaffinity=conaffinity | {".*": 0},
        condim={foot_re: 3, ".*": 1},
        priority={foot_re: 1, ".*": 0},
        friction={foot_re: _FOOT_FRICTION},
        solref=_CONTACT_SOLREF,
        solimp=_CONTACT_SOLIMP,
    )


#: Link meshes plus foot meshes. The name is still `HYBRID` because the scheme is
#: unchanged -- feet at full resolution, links reduced -- but the reduction step
#: is pending for the V1.6 model, so today both halves are the same meshes. See
#: `_LINK_MESH`.
HYBRID_COLLISION = _collision_cfg(_FOOT_MESH, _LINK_MESH)

#: The names of the colliding foot geoms; the contact sensor needs them.
FOOT_GEOMS: tuple[str, ...] = _FOOT_MESH

#: Collision geometry of the segments adjoining the toe and claw tips. To penalise
#: non-foot ground contact later, use this as the contact sensor's primary; see
#: `TIP_LINKS`.
TIP_GEOMS: tuple[str, ...] = tuple(f"{link}_meshcol" for link in TIP_LINKS)


def get_jumper_robot_cfg(
    effort_limit: float = EFFORT_LIMIT, asset: Path | None = None
) -> EntityCfg:
    """Return a fresh instance every time, so a config shared in several places
    cannot be polluted from one of them (the same approach mjlab takes for Go1).

    ``effort_limit`` is for **diagnostic experiments** only. The hardware's plateau
    is 1.7464 N*m and the servo curve bounds the torque below it at speed; do not
    produce a policy with any other value. ``asset`` overrides the model XML and
    comes from `--model`.
    """
    return EntityCfg(
        init_state=EntityCfg.InitialStateCfg(
            pos=(0.0, 0.0, STAND_Z),
            joint_pos=dict(HOME),
            joint_vel={".*": 0.0},
        ),
        collisions=(HYBRID_COLLISION,),
        spec_fn=partial(get_spec, asset),
        articulation=EntityArticulationInfoCfg(
            actuators=(make_actuator_cfg(effort_limit),),
            soft_joint_pos_limit_factor=0.9,
        ),
    )
